### ISSUE TITLE
[locate] .../v0.43.0/L.Control.Locate.js not found

### ISSUE THREAD

**Issue by fentas** [pauloborges/meteor-mapbox#17]
Hey there,
it seems `https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.js`  does not exists.
I looked into the docs and found the following (working) ressource `https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js`.

**Comment by fentas** [comment]
Makes this version completely unusable for me because nothing loads after unsuccessful resource request.

**Comment by fentas** [comment]
@pauloborges please consider to merge #14 asap.

**Comment by pauloborges** [comment]
@fentas I've merged #14 and released a new version.
