### ISSUE TITLE
Mapbox.load() with multiple plugins does not seem to work

### ISSUE THREAD

**Issue by biocross** [pauloborges/meteor-mapbox#5]
I am trying to use Mapbox with multiple plugins, namely 
'''
Mapbox.load('markercluster', 'directions'); 
'''

Whenever I do this, the map stops working - The map is not loaded at all into the DOM. Is there a problem anywhere?

**Comment by pauloborges** [comment]
Yes, there's a bug when loading multiple plugins. I'm working on a fix.

**Comment by pauloborges** [comment]
Can you test my `devel` branch? Multiple plugins is now working for me. If it's ok for you I'll release a new version.

**Comment by pauloborges** [comment]
Fixed by 0713fc9. There is a new package version: `2.1.4_3`.

**Comment by biocross** [comment]
It works now! Thanks :)
