### ISSUE TITLE
Using with urigo:angular-meteor

### ISSUE THREAD

**Issue by dagatsoin** [pauloborges/meteor-mapbox#6]
Hi, I tried to use meteor-mapbox with urigo:angular-meteor plugin. But I am stuck at the beginning. I have put this in server/startup folder.
```
Meteor.startup(function(){
    Mapbox.load();
});
```
But I get the error in the terminal `ReferenceError: Mapbox is not defined` (NB : The plugin is already added.)

Have you an idea on this ?

**Comment by pauloborges** [comment]
Hi! You have to call `Mapbox.load()` from your client code, not from the server.

**Comment by dagatsoin** [comment]
*facepalm* thx :+1:
