### ISSUE TITLE
Support for GL

### ISSUE THREAD

**Issue by Kestanous** [pauloborges/meteor-mapbox#7]
Can we get an option to switch out to https://www.mapbox.com/mapbox-gl/?

**Comment by pauloborges** [comment]
Definitely!

What do you think of?

    Mapbox.load({
        gl: boolean,
        plugins: [pluginList]
    });

Of course this will break the API, but the truth is I never liked `Mapbox.load(plugin, plugin, ...)` API and this is an "oportunity" to fix it.

**Comment by Kestanous** [comment]
Yep, looks good! This will also make adding more options later easier anyway.

**Comment by pauloborges** [comment]
Nice! I'll work on it.

**Comment by pauloborges** [comment]
Hi @Kestanous, could you test the `devel` branch?

**Comment by Kestanous** [comment]
Thanks! Looks like it works. Not sure yet because the api is very different and my app is now breaking. Got some learning to do but I definitely have the mapboxgl object.

**Comment by sbr464** [comment]
Hi Paul,

Thanks for your work on Mapbox. I can get mapbox gl to load properly with your dev branch version. I forked your package and tried updating the url to the latest gl version (below). mapboxgl will not load after doing this. I would like to use some of the new features. Do you know why this issue is happening? something breaks. Thanks

  mapboxgl: {
    js:   ['https://api.tiles.mapbox.com/mapbox-gl-js/v0.8.1/mapbox-gl.js'],
    css:  ['https://api.tiles.mapbox.com/mapbox-gl-js/v0.8.1/mapbox-gl.css'],
  },

**Comment by nakhbari** [comment]
Unlike regular MapboxJS, MapboxGL does not inherit Leaflet map. So you will be seeing problems with any of your regular leaflet code. If i get a chance, i will make a pull request to address this.

**Comment by pauloborges** [comment]
Hi @sbr464, sorry for the long delay!

I've released a new version of the package now. You can check the demo application to see how you can setup it to work:

Demo (GL): http://mapbox.meteor.com/gl 

Code: https://github.com/pauloborges/meteor-mapbox/blob/master/demo/main.js#L38-L53

**Comment by mahmoudkm** [comment]
I am trying to load Mapbox GL with directions plugin support as shown below, yet I am always getting following errors. Also code I am using shown below. Thanks

```
  TypeError: mapboxgl.Directions is not a function
    at app.js:113
    at Tracker.Computation._compute (tracker.js:331)
    at Tracker.Computation._recompute (tracker.js:350)
    at Object.Tracker._runFlush (tracker.js:489)
    at onGlobalMessage (setimmediate.js:102)

```


  ```
 Uncaught ReferenceError: L is not defined    index.js:3 
```

Line 112 in app.js contains 

`map.addControl(new mapboxgl.Directions());
`

```
   Meteor.startup(function() {
     Mapbox.debug = true;
     Mapbox.load({
        gl: true,
        plugins: ['directions']
     });
   });

```
